### ISSUE TITLE
blob fails with small image size

### ISSUE THREAD

**Issue by seanderson** [keithohara/mmyro#5]
#Unable to use blobbing with setPicsize(‘small’)
takePicture(‘blob’)
Myro is stopping: -------------------------------------------
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in showpic
  File "/usr/local/lib/python2.7/dist-packages/myro/__init__.py", line 880, in takePicture
    return myro.globvars.robot.takePicture(mode)
  File "/usr/local/lib/python2.7/dist-packages/myro/robots/scribbler.py", line 975, in takePicture
    a = self._grab_blob_array()
  File "/usr/local/lib/python2.7/dist-packages/myro/robots/scribbler.py", line 1057, in _grab_blob_array
    blobs[i * width + j+z] = val
IndexError: array assignment index out of range

**Comment by keithohara** [comment]
fixed with https://github.com/drablab/mmyro/commit/428fb0bfff98714a7ce06db5380e2114a71bfa23
